# CXX=g++
# CXXFLAGS=-std=c++11 -O2 -Wall -g

# TARGET:=myserver
# SOURCE:=$(wildcard ../*.cpp)
# OBJS=./src/buffer.cpp ./src/timer.cpp ./src/epoller.cpp ./src/webserver.cpp \
# 	 ./src/threadpoll ./src/htt ./main.cpp

# $(TARGET):$(OBJS)
# 	$(CXX) $(CXXFLAGS)  $(OBJS) -o ./bin/$(TARGET) -pthread


g++ ./src/threadpool.cpp ./src/safequeue.cpp main.cpp -o ./bin/test -pthread