
main:main.cpp ./src/epoll_function.cpp ./src/http_connect.cpp ./src/log.cpp
	g++ main.cpp ./src/epoll_function.cpp ./src/http_connect.cpp ./src/log.cpp -o main -pthread

# app.out:main.o epoll_function.o http_client_info.o http_connect.o
# 	g++ *.o -o app.out -pthread

# main.o:main.cpp 
# 	g++ main.cpp -c 
# epoll_function.o:./src/epoll_function.cpp
# 	g++ ./src/epoll_function.cpp -c 
# http_client_info.o:./src/http_client_info.cpp
# 	g++ ./src/http_client_info.cpp -c
# http_connect.o:./src/http_connect.cpp
# 	g++ ./src/http_connect.cpp -c




